In [ ]:
from google.colab import files
uploaded = files.upload()

Saving 1780800696183-sales_data.csv to 1780800696183-sales_data.csv

In [ ]:
import pandas as pd

In [ ]:
data_csv = pd.read_csv('1780800696183-sales_data.csv')

In [ ]:
data_csv = pd.read_csv('/content/1780800696183-sales_data.csv')

In [ ]:
sales_data = pd.DataFrame(data_csv)

In [ ]:
sales_data

  order_id,order_date,customer_name,product_category,product_name,quantity,unit_price,total_amount,salesperson,region
0  1001,2026-01-05,Andi Saputra,Electronics,Wirel...
1  1002,2026-01-07,Siti Aminah,Home,Blender,1,45....
2  1003,2026-01-08,Budi Santoso,Fashion,T-Shirt,3...
3  1004,2026-01-10,Dewi Lestari,Electronics,Keybo...
4  1005,2026-01-11,Rizky Pratama,Sports,Yoga Mat,...
5  1006,2026-01-12,Maya Putri,Home,Vacuum Cleaner...
6  1007,2026-01-13,Fajar Nugroho,Fashion,Jeans,2,...
7  1008,2026-01-15,Nina Kartika,Electronics,Webca...
8  1009,2026-01-16,Hendra Wijaya,Sports,Dumbbell ...
9  1010,2026-01-18,Lisa Maharani,Home,Air Fryer,1...

IMPORT FILE  EXCEL

In [ ]:
import pandas as pd

data_excel = pd.read_excel('/content/1780800683047-laporan.xlsx')
data_excel

,order_id,order_date,customer_name,product_category,product_name,quantity,unit_price,total_amount,salesperson,region
0,1001,46027,Andi Saputra,Electronics,Wireless Mouse,2,15.5,31,Rina,Jakarta
1,1002,46029,Siti Aminah,Home,Blender,1,45.0,45,Budi,Bandung
2,1003,46030,Budi Santoso,Fashion,T-Shirt,3,12.0,36,Rina,Surabaya
3,1004,46032,Dewi Lestari,Electronics,Keyboard,1,28.0,28,Andi,Jakarta
4,1005,46033,Rizky Pratama,Sports,Yoga Mat,2,20.0,40,Budi,Yogyakarta
5,1006,46034,Maya Putri,Home,Vacuum Cleaner,1,120.0,120,Rina,Medan
6,1007,46035,Fajar Nugroho,Fashion,Jeans,2,35.0,70,Andi,Semarang
7,1008,46037,Nina Kartika,Electronics,Webcam,1,55.0,55,Budi,Batam
8,1009,46038,Hendra Wijaya,Sports,Dumbbell Set,1,75.0,75,Rina,Jakarta
9,1010,46040,Lisa Maharani,Home,Air Fryer,1,90.0,90,Andi,Bandung

In [ ]:
tab_ringkasan = pd.read_excel(
    '/content/1780800683047-laporan.xlsx', #nama filenya apa
    sheet_name='Ringkasan' # tab mana yg mau ditampilkan
)

tab_ringkasan

         Unnamed: 0       Unnamed: 1           Unnamed: 2
0               NaN              NaN                  NaN
1  product_category  Sum of quantity  Sum of total_amount
2       Electronics                4                  114
3           Fashion                5                  106
4              Home                3                  255
5            Sports                3                  115
6       Grand Total               15                  590

In [ ]:
all_tab = pd.read_excel(
    '/content/1780800683047-laporan.xlsx',
    sheet_name= None
)

all_tab

{'Penjualan':    order_id  order_date  customer_name product_category    product_name  \
 0      1001       46027   Andi Saputra      Electronics  Wireless Mouse
 1      1002       46029    Siti Aminah             Home         Blender
 2      1003       46030   Budi Santoso          Fashion         T-Shirt
 3      1004       46032   Dewi Lestari      Electronics        Keyboard
 4      1005       46033  Rizky Pratama           Sports        Yoga Mat
 5      1006       46034     Maya Putri             Home  Vacuum Cleaner
 6      1007       46035  Fajar Nugroho          Fashion           Jeans
 7      1008       46037   Nina Kartika      Electronics          Webcam
 8      1009       46038  Hendra Wijaya           Sports    Dumbbell Set
 9      1010       46040  Lisa Maharani             Home       Air Fryer

    quantity  unit_price  total_amount salesperson      region
 0         2        15.5            31        Rina     Jakarta
 1         1        45.0            45        Budi     Bandung
 2         3        12.0            36        Rina    Surabaya
 3         1        28.0            28        Andi     Jakarta
 4         2        20.0            40        Budi  Yogyakarta
 5         1       120.0           120        Rina       Medan
 6         2        35.0            70        Andi    Semarang
 7         1        55.0            55        Budi       Batam
 8         1        75.0            75        Rina     Jakarta
 9         1        90.0            90        Andi     Bandung  ,
 'Ringkasan':          Unnamed: 0       Unnamed: 1           Unnamed: 2
 0               NaN              NaN                  NaN
 1  product_category  Sum of quantity  Sum of total_amount
 2       Electronics                4                  114
 3           Fashion                5                  106
 4              Home                3                  255
 5            Sports                3                  115
 6       Grand Total               15                  590}

Import Google Sheet

In [ ]:
sheet_id = '1-RumBJVQZXfUDIUDv7DUWutJkAA9vzGv7d9kPtYFcIE'
sheet_url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv'

import pandas as pd

data_student = pd.read_csv(sheet_url)
data_student

  order_id,order_date,customer_name,product_category,product_name,quantity,unit_price,total_amount,salesperson,region
0  1001,2026-01-05,Andi Saputra,Electronics,Wirel...
1  1002,2026-01-07,Siti Aminah,Home,Blender,1,45....
2  1003,2026-01-08,Budi Santoso,Fashion,T-Shirt,3...
3  1004,2026-01-10,Dewi Lestari,Electronics,Keybo...
4  1005,2026-01-11,Rizky Pratama,Sports,Yoga Mat,...
5  1006,2026-01-12,Maya Putri,Home,Vacuum Cleaner...
6  1007,2026-01-13,Fajar Nugroho,Fashion,Jeans,2,...
7  1008,2026-01-15,Nina Kartika,Electronics,Webca...
8  1009,2026-01-16,Hendra Wijaya,Sports,Dumbbell ...
9  1010,2026-01-18,Lisa Maharani,Home,Air Fryer,1...

In [ ]:
data_student

  order_id,order_date,customer_name,product_category,product_name,quantity,unit_price,total_amount,salesperson,region
0  1001,2026-01-05,Andi Saputra,Electronics,Wirel...
1  1002,2026-01-07,Siti Aminah,Home,Blender,1,45....
2  1003,2026-01-08,Budi Santoso,Fashion,T-Shirt,3...
3  1004,2026-01-10,Dewi Lestari,Electronics,Keybo...
4  1005,2026-01-11,Rizky Pratama,Sports,Yoga Mat,...
5  1006,2026-01-12,Maya Putri,Home,Vacuum Cleaner...
6  1007,2026-01-13,Fajar Nugroho,Fashion,Jeans,2,...
7  1008,2026-01-15,Nina Kartika,Electronics,Webca...
8  1009,2026-01-16,Hendra Wijaya,Sports,Dumbbell ...
9  1010,2026-01-18,Lisa Maharani,Home,Air Fryer,1...

In [ ]:
import requests

url = 'https://jsonplaceholder.typicode.com/posts/3'

response = requests.get(url)

if response.status_code == 200:
  # print(response.json())
  data_ka_naela = response.json()
  print('ID: ', data_ka_naela['id'])
  print('Title: ', data_ka_naela['title'])
else:
  print('Error')

ID:  3
Title:  ea molestias quasi exercitationem repellat qui ipsa sit aut

In [ ]:
import requests

url = 'https://jsonplaceholder.typicode.com/posts/4'

response = requests.get(url)
response

In [ ]:
import requests

url = 'https://jsonplaceholder.typicode.com/posts/3'

response = requests.get(url)

if response.status_code == 200:
  # print(response.json())
  data_ka_naela = response.json()
  print('ID: ', data_ka_naela['id'])
  print('Title: ', data_ka_naela['title'])

ID:  3
Title:  ea molestias quasi exercitationem repellat qui ipsa sit aut

Create Datase

1. Define purpose

rata-rata nilai student di setiap mapel

student_id

student_name

subject

score

2. Definisikan tipe data

student_id(Integer)

student_nama(string/Text)

subject(STRING): ada 4 pilihan

score (INTEGER)

-- numpy
- student_id
- score

-- faker
- student_name

In [ ]:
pip install faker

Collecting faker
  Downloading faker-40.22.0-py3-none-any.whl.metadata (16 kB)
Downloading faker-40.22.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 88.2 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.22.0

In [ ]:
from faker import Faker
import numpy as np

wadah_data = []
fake = Faker('id_ID')

for i in range(1000):
  student_id = np.random.randint(10000,20000)
  student_name = fake.name()

  subject_options = ['IPA','IPS','English','Math']
  subject = np.random.choice(subject_options)

  score = np.random.randint(0,101)

  satu_data_siswa = {
      'student_id': student_id,
      'student_name': student_name,
      'subject': subject,
      'score': score
  }

  wadah_data.append(satu_data_siswa)

print(wadah_data)

[{'student_id': 13502, 'student_name': 'Puspa Farida', 'subject': np.str_('IPA'), 'score': 46}, {'student_id': 10835, 'student_name': 'Dimaz Santoso', 'subject': np.str_('IPA'), 'score': 14}, {'student_id': 19422, 'student_name': 'Ozy Putra', 'subject': np.str_('IPS'), 'score': 91}, {'student_id': 18386, 'student_name': 'Rachel Widiastuti', 'subject': np.str_('IPS'), 'score': 58}, {'student_id': 12256, 'student_name': 'Nova Sihombing, S.I.Kom', 'subject': np.str_('IPS'), 'score': 61}, {'student_id': 18479, 'student_name': 'Padmi Latupono', 'subject': np.str_('IPA'), 'score': 80}, {'student_id': 17192, 'student_name': 'KH. Kemba Pertiwi, S.T.', 'subject': np.str_('Math'), 'score': 26}, {'student_id': 17829, 'student_name': 'Cakrajiya Tarihoran', 'subject': np.str_('IPA'), 'score': 3}, {'student_id': 17827, 'student_name': 'drg. Ana Utama, M.M.', 'subject': np.str_('IPA'), 'score': 20}, {'student_id': 12997, 'student_name': 'Yunita Hutapea', 'subject': np.str_('IPA'), 'score': 57}, {'student_id': 18186, 'student_name': 'Prakosa Suwarno', 'subject': np.str_('English'), 'score': 18}, {'student_id': 15967, 'student_name': 'Ifa Damanik', 'subject': np.str_('IPA'), 'score': 39}, {'student_id': 18021, 'student_name': 'Sadina Laksita', 'subject': np.str_('Math'), 'score': 99}, {'student_id': 12708, 'student_name': 'Drs. Lamar Agustina', 'subject': np.str_('Math'), 'score': 44}, {'student_id': 13253, 'student_name': 'Ulva Pangestu', 'subject': np.str_('IPS'), 'score': 9}, {'student_id': 17615, 'student_name': 'R.A. Padmi Kuswandari', 'subject': np.str_('Math'), 'score': 87}, {'student_id': 18536, 'student_name': 'Julia Marbun', 'subject': np.str_('IPS'), 'score': 33}, {'student_id': 17654, 'student_name': 'Clara Kusumo', 'subject': np.str_('IPS'), 'score': 92}, {'student_id': 15742, 'student_name': 'Sabrina Usamah, S.Gz', 'subject': np.str_('Math'), 'score': 98}, {'student_id': 12890, 'student_name': 'Kawaya Prakasa', 'subject': np.str_('English'), 'score': 22}, {'student_id': 12596, 'student_name': 'Saadat Nasyidah', 'subject': np.str_('IPA'), 'score': 15}, {'student_id': 11199, 'student_name': 'dr. Nardi Simanjuntak', 'subject': np.str_('IPA'), 'score': 6}, {'student_id': 18626, 'student_name': 'Hamima Wibisono, S.H.', 'subject': np.str_('IPA'), 'score': 25}, {'student_id': 13872, 'student_name': 'Jamalia Farida', 'subject': np.str_('IPA'), 'score': 92}, {'student_id': 16077, 'student_name': 'R. Darijan Mandala, M.Ak', 'subject': np.str_('IPS'), 'score': 65}, {'student_id': 16817, 'student_name': 'Najib Pudjiastuti', 'subject': np.str_('IPS'), 'score': 18}, {'student_id': 13409, 'student_name': 'Dipa Habibi', 'subject': np.str_('English'), 'score': 61}, {'student_id': 12968, 'student_name': 'Ir. Eva Hutagalung', 'subject': np.str_('IPS'), 'score': 79}, {'student_id': 17835, 'student_name': 'R.M. Hairyanto Purwanti, S.Pt', 'subject': np.str_('IPS'), 'score': 27}, {'student_id': 19390, 'student_name': 'Maya Damanik', 'subject': np.str_('IPS'), 'score': 96}, {'student_id': 16123, 'student_name': 'Bahuraksa Puspasari', 'subject': np.str_('IPS'), 'score': 62}, {'student_id': 17581, 'student_name': 'Darijan Usada', 'subject': np.str_('IPS'), 'score': 34}, {'student_id': 17345, 'student_name': 'Karsa Saefullah, M.Farm', 'subject': np.str_('Math'), 'score': 0}, {'student_id': 10799, 'student_name': 'T. Rahman Handayani, S.Gz', 'subject': np.str_('English'), 'score': 32}, {'student_id': 10218, 'student_name': 'Imam Utami', 'subject': np.str_('IPA'), 'score': 33}, {'student_id': 10195, 'student_name': 'Tgk. Elma Saragih, S.Farm', 'subject': np.str_('IPS'), 'score': 75}, {'student_id': 16497, 'student_name': 'drg. Mulyanto Sihotang', 'subject': np.str_('IPS'), 'score': 83}, {'student_id': 15127, 'student_name': 'Puput Rahayu', 'subject': np.str_('IPA'), 'score': 36}, {'student_id': 15727, 'student_name': 'Betania Nasyiah', 'subject': np.str_('IPS'), 'score': 23}, {'student_id': 16382, 'student_name': 'Narji Situmorang, S.Pd', 'subject': np.str_('Math'), 'score': 46}, {'student_id': 12437, 'student_name': 'Banawi Palastri', 'subject': np.str_('IPS'), 'score': 57}, {'student_id': 10592, 'student_name': 'Qori Marbun', 'subject': np.str_('IPA'), 'score': 54}, {'student_id': 17409, 'student_name': 'drg. Dewi Pudjiastuti', 'subject': np.str_('Math'), 'score': 1}, {'student_id': 10621, 'student_name': 'Dr. Maryanto Rajata', 'subject': np.str_('Math'), 'score': 53}, {'student_id': 17700, 'student_name': 'Pandu Nasyidah', 'subject': np.str_('Math'), 'score': 32}, {'student_id': 19294, 'student_name': 'Eja Marpaung', 'subject': np.str_('IPA'), 'score': 13}, {'student_id': 11665, 'student_name': 'Yuni Siregar', 'subject': np.str_('Math'), 'score': 59}, {'student_id': 16431, 'student_name': 'Ivan Santoso', 'subject': np.str_('Math'), 'score': 82}, {'student_id': 11005, 'student_name': 'KH. Opan Prastuti, S.Kom', 'subject': np.str_('IPA'), 'score': 31}, {'student_id': 11767, 'student_name': 'R.A. Titi Habibi', 'subject': np.str_('IPA'), 'score': 96}, {'student_id': 12464, 'student_name': 'Jindra Ardianto', 'subject': np.str_('English'), 'score': 21}, {'student_id': 13725, 'student_name': 'Ir. Salwa Utami', 'subject': np.str_('English'), 'score': 10}, {'student_id': 13016, 'student_name': 'Wulan Wastuti', 'subject': np.str_('IPA'), 'score': 96}, {'student_id': 10510, 'student_name': 'Hj. Queen Hutasoit, S.Psi', 'subject': np.str_('English'), 'score': 79}, {'student_id': 16728, 'student_name': 'Kartika Hardiansyah', 'subject': np.str_('IPS'), 'score': 81}, {'student_id': 17210, 'student_name': 'Nadia Hidayanto', 'subject': np.str_('IPS'), 'score': 57}, {'student_id': 13557, 'student_name': 'Tgk. Xanana Pradana', 'subject': np.str_('IPA'), 'score': 51}, {'student_id': 15147, 'student_name': 'Dr. Silvia Suryatmi, S.Kom', 'subject': np.str_('IPS'), 'score': 74}, {'student_id': 18261, 'student_name': 'Kamila Kuswandari', 'subject': np.str_('English'), 'score': 4}, {'student_id': 12331, 'student_name': 'drg. Clara Ramadan, S.Pd', 'subject': np.str_('Math'), 'score': 48}, {'student_id': 15959, 'student_name': 'Drs. Among Yulianti', 'subject': np.str_('English'), 'score': 97}, {'student_id': 16941, 'student_name': 'R. Elma Mahendra', 'subject': np.str_('Math'), 'score': 42}, {'student_id': 15925, 'student_name': 'Darsirah Melani', 'subject': np.str_('English'), 'score': 86}, {'student_id': 17552, 'student_name': 'Yance Maryadi', 'subject': np.str_('Math'), 'score': 67}, {'student_id': 10433, 'student_name': 'Puti Bella Samosir', 'subject': np.str_('English'), 'score': 23}, {'student_id': 11813, 'student_name': 'Rachel Prakasa, S.E.', 'subject': np.str_('Math'), 'score': 82}, {'student_id': 13161, 'student_name': 'Vicky Salahudin', 'subject': np.str_('IPS'), 'score': 42}, {'student_id': 16640, 'student_name': 'Wani Wasita, M.M.', 'subject': np.str_('English'), 'score': 67}, {'student_id': 18500, 'student_name': 'Puji Latupono', 'subject': np.str_('IPA'), 'score': 5}, {'student_id': 18990, 'student_name': 'Patricia Firmansyah', 'subject': np.str_('English'), 'score': 22}, {'student_id': 11150, 'student_name': 'Cakrawala Wijayanti', 'subject': np.str_('IPS'), 'score': 75}, {'student_id': 18541, 'student_name': 'Daryani Saptono', 'subject': np.str_('IPA'), 'score': 78}, {'student_id': 10032, 'student_name': 'Hj. Kani Zulaika, S.Kom', 'subject': np.str_('IPS'), 'score': 30}, {'student_id': 16529, 'student_name': 'Tina Mahendra, S.T.', 'subject': np.str_('IPS'), 'score': 81}, {'student_id': 14227, 'student_name': 'Cut Silvia Nuraini, S.Sos', 'subject': np.str_('IPA'), 'score': 59}, {'student_id': 10724, 'student_name': 'Taswir Riyanti', 'subject': np.str_('IPA'), 'score': 85}, {'student_id': 19357, 'student_name': 'R.A. Diana Haryanti, S.E.I', 'subject': np.str_('Math'), 'score': 34}, {'student_id': 19946, 'student_name': 'Sakti Suryono', 'subject': np.str_('Math'), 'score': 47}, {'student_id': 12004, 'student_name': 'Hasna Uwais', 'subject': np.str_('IPS'), 'score': 92}, {'student_id': 19976, 'student_name': 'Intan Utami', 'subject': np.str_('English'), 'score': 77}, {'student_id': 18889, 'student_name': 'Tami Mandasari', 'subject': np.str_('Math'), 'score': 95}, {'student_id': 17478, 'student_name': 'Warta Mangunsong, S.H.', 'subject': np.str_('IPA'), 'score': 4}, {'student_id': 10976, 'student_name': 'R. Natalia Hidayat', 'subject': np.str_('IPS'), 'score': 14}, {'student_id': 16415, 'student_name': 'Ghaliyati Mandala', 'subject': np.str_('English'), 'score': 82}, {'student_id': 13282, 'student_name': 'Zamira Ardianto', 'subject': np.str_('English'), 'score': 88}, {'student_id': 18349, 'student_name': 'Tania Yuliarti', 'subject': np.str_('IPS'), 'score': 97}, {'student_id': 10333, 'student_name': 'Maida Gunarto', 'subject': np.str_('IPA'), 'score': 78}, {'student_id': 11434, 'student_name': 'Warsita Waluyo, M.Ak', 'subject': np.str_('IPA'), 'score': 96}, {'student_id': 14885, 'student_name': 'dr. Nalar Samosir, S.Psi', 'subject': np.str_('English'), 'score': 3}, {'student_id': 14047, 'student_name': 'Cahyanto Kusumo', 'subject': np.str_('Math'), 'score': 21}, {'student_id': 12731, 'student_name': 'Ir. Dewi Haryanti', 'subject': np.str_('IPS'), 'score': 37}, {'student_id': 18740, 'student_name': 'Yahya Hassanah, M.Ak', 'subject': np.str_('IPS'), 'score': 51}, {'student_id': 11808, 'student_name': 'Praba Suwarno', 'subject': np.str_('IPA'), 'score': 77}, {'student_id': 18811, 'student_name': 'Sutan Dalimin Wahyudin, S.Kom', 'subject': np.str_('IPS'), 'score': 19}, {'student_id': 16666, 'student_name': 'Dodo Uyainah', 'subject': np.str_('IPA'), 'score': 100}, {'student_id': 11557, 'student_name': 'Ir. Aditya Wasita, M.Kom.', 'subject': np.str_('Math'), 'score': 93}, {'student_id': 15959, 'student_name': 'Drajat Andriani', 'subject': np.str_('English'), 'score': 47}, {'student_id': 18460, 'student_name': 'Kacung Prabowo, S.Pd', 'subject': np.str_('English'), 'score': 87}, {'student_id': 18438, 'student_name': 'Gara Hariyah', 'subject': np.str_('English'), 'score': 47}, {'student_id': 12432, 'student_name': 'drg. Rahayu Prakasa', 'subject': np.str_('IPS'), 'score': 44}, {'student_id': 14701, 'student_name': 'Sari Hidayat', 'subject': np.str_('Math'), 'score': 12}, {'student_id': 19037, 'student_name': 'drg. Unjani Pudjiastuti', 'subject': np.str_('IPS'), 'score': 47}, {'student_id': 19876, 'student_name': 'Gada Laksita', 'subject': np.str_('Math'), 'score': 37}, {'student_id': 15707, 'student_name': 'Adiarja Hardiansyah, S.E.I', 'subject': np.str_('IPS'), 'score': 84}, {'student_id': 17650, 'student_name': 'R.M. Hari Narpati', 'subject': np.str_('IPA'), 'score': 54}, {'student_id': 14909, 'student_name': 'Iriana Napitupulu, S.T.', 'subject': np.str_('IPA'), 'score': 48}, {'student_id': 12348, 'student_name': 'Xanana Mandala', 'subject': np.str_('IPA'), 'score': 61}, {'student_id': 13430, 'student_name': 'R. Puspa Suartini, S.Kom', 'subject': np.str_('English'), 'score': 0}, {'student_id': 10046, 'student_name': 'Dt. Candrakanta Pratiwi', 'subject': np.str_('IPA'), 'score': 31}, {'student_id': 10039, 'student_name': 'dr. Aswani Megantara, S.Psi', 'subject': np.str_('IPA'), 'score': 45}, {'student_id': 19113, 'student_name': 'Puspa Mustofa', 'subject': np.str_('English'), 'score': 75}, {'student_id': 12991, 'student_name': 'Elon Sihombing', 'subject': np.str_('English'), 'score': 95}, {'student_id': 10495, 'student_name': 'Najam Prasetyo, M.Pd', 'subject': np.str_('IPS'), 'score': 29}, {'student_id': 17610, 'student_name': 'Cahyanto Sirait', 'subject': np.str_('English'), 'score': 52}, {'student_id': 17102, 'student_name': 'Suci Utami', 'subject': np.str_('IPA'), 'score': 83}, {'student_id': 12649, 'student_name': 'dr. Warsa Zulaika, S.T.', 'subject': np.str_('English'), 'score': 76}, {'student_id': 10838, 'student_name': 'Legawa Pudjiastuti, M.TI.', 'subject': np.str_('IPS'), 'score': 7}, {'student_id': 12542, 'student_name': 'Sutan Edison Nurdiyanti, M.TI.', 'subject': np.str_('Math'), 'score': 33}, {'student_id': 12667, 'student_name': 'Raina Winarno, S.H.', 'subject': np.str_('Math'), 'score': 0}, {'student_id': 14937, 'student_name': 'Jatmiko Hariyah', 'subject': np.str_('English'), 'score': 14}, {'student_id': 10074, 'student_name': 'Ami Padmasari', 'subject': np.str_('IPS'), 'score': 32}, {'student_id': 13351, 'student_name': 'Umi Novitasari, S.Pd', 'subject': np.str_('IPA'), 'score': 77}, {'student_id': 15047, 'student_name': 'T. Pandu Hakim, S.Sos', 'subject': np.str_('Math'), 'score': 32}, {'student_id': 15156, 'student_name': 'Ir. Hana Hidayat', 'subject': np.str_('English'), 'score': 96}, {'student_id': 15061, 'student_name': 'Sari Gunawan', 'subject': np.str_('IPA'), 'score': 63}, {'student_id': 19633, 'student_name': 'Latika Winarsih', 'subject': np.str_('English'), 'score': 31}, {'student_id': 10919, 'student_name': 'Sakti Laksmiwati', 'subject': np.str_('IPS'), 'score': 59}, {'student_id': 14387, 'student_name': 'Usyi Marbun', 'subject': np.str_('English'), 'score': 47}, {'student_id': 19411, 'student_name': 'R. Karya Napitupulu', 'subject': np.str_('IPA'), 'score': 25}, {'student_id': 18974, 'student_name': 'Rahman Mahendra', 'subject': np.str_('IPS'), 'score': 59}, {'student_id': 18337, 'student_name': 'Laksana Adriansyah', 'subject': np.str_('IPA'), 'score': 10}, {'student_id': 11227, 'student_name': 'H. Cahyadi Utami, S.IP', 'subject': np.str_('Math'), 'score': 71}, {'student_id': 11724, 'student_name': 'Belinda Saefullah', 'subject': np.str_('Math'), 'score': 80}, {'student_id': 17491, 'student_name': 'Cinthia Maheswara, S.E.', 'subject': np.str_('IPS'), 'score': 22}, {'student_id': 13060, 'student_name': 'Febi Jailani', 'subject': np.str_('Math'), 'score': 29}, {'student_id': 10144, 'student_name': 'Siska Melani', 'subject': np.str_('English'), 'score': 22}, {'student_id': 15154, 'student_name': 'Balamantri Suartini, M.Kom.', 'subject': np.str_('English'), 'score': 34}, {'student_id': 14711, 'student_name': 'Laras Mansur, S.IP', 'subject': np.str_('IPS'), 'score': 42}, {'student_id': 17392, 'student_name': 'Pangeran Waskita, S.Pd', 'subject': np.str_('IPS'), 'score': 17}, {'student_id': 13309, 'student_name': 'Warsa Nashiruddin', 'subject': np.str_('IPA'), 'score': 26}, {'student_id': 14922, 'student_name': 'Jessica Wibisono', 'subject': np.str_('English'), 'score': 67}, {'student_id': 13478, 'student_name': 'drg. Tari Oktaviani, S.E.I', 'subject': np.str_('English'), 'score': 84}, {'student_id': 15081, 'student_name': 'Nyana Melani, S.E.I', 'subject': np.str_('English'), 'score': 10}, {'student_id': 19872, 'student_name': 'Alika Saefullah', 'subject': np.str_('IPA'), 'score': 89}, {'student_id': 13044, 'student_name': 'Dewi Sitorus', 'subject': np.str_('Math'), 'score': 85}, {'student_id': 14625, 'student_name': 'Luthfi Widiastuti, M.Kom.', 'subject': np.str_('English'), 'score': 14}, {'student_id': 14399, 'student_name': 'Emin Prasetyo', 'subject': np.str_('IPA'), 'score': 7}, {'student_id': 13174, 'student_name': 'Puspa Wibowo', 'subject': np.str_('IPS'), 'score': 45}, {'student_id': 16569, 'student_name': 'Caraka Anggraini, S.Sos', 'subject': np.str_('Math'), 'score': 33}, {'student_id': 14387, 'student_name': 'Raina Sirait, S.Farm', 'subject': np.str_('English'), 'score': 96}, {'student_id': 16716, 'student_name': 'Keisha Hutapea', 'subject': np.str_('English'), 'score': 66}, {'student_id': 10431, 'student_name': 'Dr. Heryanto Santoso', 'subject': np.str_('IPA'), 'score': 74}, {'student_id': 16738, 'student_name': 'Jaiman Puspita, M.Ak', 'subject': np.str_('Math'), 'score': 31}, {'student_id': 15413, 'student_name': 'Hj. Eka Safitri, M.Ak', 'subject': np.str_('IPA'), 'score': 26}, {'student_id': 15453, 'student_name': 'Garang Tamba', 'subject': np.str_('IPS'), 'score': 55}, {'student_id': 17066, 'student_name': 'Keisha Damanik', 'subject': np.str_('IPS'), 'score': 40}, {'student_id': 11129, 'student_name': 'Faizah Waskita', 'subject': np.str_('English'), 'score': 5}, {'student_id': 12188, 'student_name': 'Panji Wastuti, M.M.', 'subject': np.str_('IPA'), 'score': 24}, {'student_id': 18466, 'student_name': 'Perkasa Samosir', 'subject': np.str_('IPA'), 'score': 3}, {'student_id': 11378, 'student_name': 'Harja Yuniar', 'subject': np.str_('Math'), 'score': 88}, {'student_id': 14851, 'student_name': 'Yessi Nasyiah', 'subject': np.str_('IPS'), 'score': 57}, {'student_id': 13749, 'student_name': 'Irwan Nashiruddin', 'subject': np.str_('IPA'), 'score': 50}, {'student_id': 15865, 'student_name': 'Cut Ciaobella Wijaya, M.Pd', 'subject': np.str_('Math'), 'score': 51}, {'student_id': 16761, 'student_name': 'Labuh Mustofa, S.Kom', 'subject': np.str_('IPS'), 'score': 79}, {'student_id': 16149, 'student_name': 'Dt. Prakosa Wahyudin, M.TI.', 'subject': np.str_('IPA'), 'score': 64}, {'student_id': 14839, 'student_name': 'Anita Mangunsong', 'subject': np.str_('IPA'), 'score': 81}, {'student_id': 19415, 'student_name': 'Tgk. Kusuma Anggriawan, S.Ked', 'subject': np.str_('IPS'), 'score': 55}, {'student_id': 13304, 'student_name': 'Ina Uyainah', 'subject': np.str_('IPS'), 'score': 28}, {'student_id': 11045, 'student_name': 'Marsito Susanti', 'subject': np.str_('English'), 'score': 70}, {'student_id': 19860, 'student_name': 'Dalima Nuraini, S.Ked', 'subject': np.str_('IPS'), 'score': 47}, {'student_id': 16751, 'student_name': 'Labuh Dabukke', 'subject': np.str_('IPA'), 'score': 52}, {'student_id': 12596, 'student_name': 'Zaenab Narpati', 'subject': np.str_('IPS'), 'score': 26}, {'student_id': 17099, 'student_name': 'Saka Sihotang', 'subject': np.str_('IPA'), 'score': 20}, {'student_id': 12608, 'student_name': 'R. Wakiman Megantara', 'subject': np.str_('IPS'), 'score': 97}, {'student_id': 17462, 'student_name': 'Elma Usamah', 'subject': np.str_('English'), 'score': 81}, {'student_id': 15065, 'student_name': 'Genta Hutasoit', 'subject': np.str_('IPA'), 'score': 42}, {'student_id': 16987, 'student_name': 'Puti Yessi Puspita, S.I.Kom', 'subject': np.str_('IPA'), 'score': 85}, {'student_id': 19772, 'student_name': 'Salsabila Oktaviani', 'subject': np.str_('IPA'), 'score': 77}, {'student_id': 19989, 'student_name': 'Padma Permata', 'subject': np.str_('Math'), 'score': 70}, {'student_id': 19375, 'student_name': 'Ir. Amalia Hidayanto', 'subject': np.str_('IPS'), 'score': 32}, {'student_id': 16204, 'student_name': 'drg. Luluh Padmasari, S.Pd', 'subject': np.str_('English'), 'score': 46}, {'student_id': 14691, 'student_name': 'Nugraha Adriansyah', 'subject': np.str_('IPS'), 'score': 17}, {'student_id': 16708, 'student_name': 'Karma Ramadan', 'subject': np.str_('IPA'), 'score': 49}, {'student_id': 19419, 'student_name': 'Queen Kuswoyo', 'subject': np.str_('Math'), 'score': 59}, {'student_id': 17094, 'student_name': 'Suci Lestari', 'subject': np.str_('IPS'), 'score': 63}, {'student_id': 19215, 'student_name': 'Cut Tira Tamba, M.Pd', 'subject': np.str_('English'), 'score': 95}, {'student_id': 16910, 'student_name': 'Gadang Halim', 'subject': np.str_('IPA'), 'score': 29}, {'student_id': 19256, 'student_name': 'Patricia Hardiansyah', 'subject': np.str_('IPA'), 'score': 35}, {'student_id': 13166, 'student_name': 'drg. Vivi Riyanti, S.E.', 'subject': np.str_('IPS'), 'score': 15}, {'student_id': 19510, 'student_name': 'Kenari Widiastuti, S.I.Kom', 'subject': np.str_('English'), 'score': 41}, {'student_id': 18679, 'student_name': 'drg. Cinthia Fujiati, M.Farm', 'subject': np.str_('Math'), 'score': 28}, {'student_id': 12234, 'student_name': 'Diana Wahyudin, M.Pd', 'subject': np.str_('IPA'), 'score': 81}, {'student_id': 10274, 'student_name': 'Ir. Maya Wahyuni', 'subject': np.str_('IPA'), 'score': 68}, {'student_id': 10798, 'student_name': 'Dewi Namaga', 'subject': np.str_('English'), 'score': 63}, {'student_id': 15834, 'student_name': 'Salsabila Saptono', 'subject': np.str_('IPA'), 'score': 85}, {'student_id': 19887, 'student_name': 'dr. Tira Hariyah, S.H.', 'subject': np.str_('Math'), 'score': 77}, {'student_id': 18035, 'student_name': 'Sutan Karja Maheswara', 'subject': np.str

In [ ]:
import pandas as pd

student_table = pd.DataFrame(wadah_data)
student_table

     student_id             student_name  subject  score
0         13502             Puspa Farida      IPA     46
1         10835            Dimaz Santoso      IPA     14
2         19422                Ozy Putra      IPS     91
3         18386        Rachel Widiastuti      IPS     58
4         12256  Nova Sihombing, S.I.Kom      IPS     61
..          ...                      ...      ...    ...
995       18123       Ir. Zulfa Purwanti  English      4
996       11347    Dian Laksmiwati, S.IP      IPA     99
997       16436             Ika Latupono  English      7
998       16913         Margana Prasetyo      IPA     54
999       18200           Tania Pangestu     Math     81

[1000 rows x 4 columns]